{{- include "chart.tpl" . | nindent 0 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-registry-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-registry
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.tlsSecret.name }}
