{{- include "chart.tpl" . | nindent 0 }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-image-registry-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}
  volumeName: {{ .Release.Name }}-image-registry
