{{- include "chart.tpl" . | nindent 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
