apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      autoindex on;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      location /secure {
        alias /usr/share/nginx/html/secure;
        index index.html;
        try_files $uri $uri/ =404;
      }
      location /insecure {
        alias /usr/share/nginx/html/insecure;
        index index.html;
      }
    }
